language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvn
script: ./mvnw clean install
jobs:
  include:
    -stage: Test
     script: ./mvnw clean test
notifications:
  email: manalensa20@gmail.com

  
 